### ISSUE TITLE
Add Quickstart page and extend Introduction

### ISSUE THREAD

**Issue by etomaselli** [scc-digitalhub/docs#1]

**Comment by etomaselli** [comment]
Expand Introduction with an overview of the platform (e.g. see MLFlow docs - What is MLFlow). Add Quickstart page with links to scenarios.

**Comment by alb-car** [comment]
Done in [ccae9b1](https://github.com/scc-digitalhub/docs/commit/ccae9b165962a3d318d1a094bce1a34620c9a8bc).
