### ISSUE TITLE
docs formatting 

### ISSUE THREAD

**Issue by nawaz2013** [scc-digitalhub/docs#15]
https://scc-digitalhub.github.io/docs/0.8

the landing page is occupied. Needs to be formatted

![image](https://github.com/user-attachments/assets/f1afe631-214e-4a33-a342-8f8dc762acfe)

**Comment by nawaz2013** [comment]
Seems that document for version 0.8 is missing for e.g the link for previous version works fine

https://scc-digitalhub.github.io/docs/0.7

**Comment by alb-car** [comment]
404 page has been replaced with properly formatted one in 7f9ee54 and 0.8 branch has been created.
